version: '3'
services:
  scrapy:
    env_file: ./.env
    build:
      context: .
      dockerfile: ./docker/scrapy/Dockerfile
      args:
        - 'SCRAPY_VERSION=${SCRAPY_VERSION}'
    tty: true
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}'
